### ISSUE TITLE
Text error on the pages

### ISSUE THREAD

**Issue by vikgor** [bludit-themes/keep-it-simple#2]
Installed the updated theme with v. 3.0.0, works fine but one thing keep popping up:
Whenever I go to a specific page on the website, I see the page, the title and everything just fine but instead of the text of the post I get this on every page (expect for static pages I guess):

Notice: Undefined variable: Page in WEBSITE/bl-themes/keep-it-simple-2.0/php/page.php on line 68
Fatal error: Uncaught Error: Call to a member function tags() on null...

Tried on freshly installed Bludit 3.0.0, other themes don't show that.

Is there a problem on my side maybe?

**Comment by clickwork-git** [comment]
Thank you for reporting the issue.

It's fixed (v2.1).
